### ISSUE TITLE
Website is behind Git

### ISSUE THREAD

**Issue by ntrel** [vlang/website#22]
Would be nice to update site for these:

https://vlang.io/docs#codegen is missing #4.
https://vlang.io/compare is missing #6.

**Comment by medvednikov** [comment]
This was fixed several days ago. I've finally made this the one and only repo, so all changes will be here right away.

**Comment by ntrel** [comment]
Pull #4 is still not live.

(Splitting the safety item in comparison from #6 is not there, but I assume that was a deliberate decision)
